### ISSUE TITLE
Certain jutsu aren't gaining exp correctly

### ISSUE THREAD

**Issue by Kiochii** [IllusiveBIair/Naruto-Evolution-Community#18]
Hi, I'm training this jutsu: Fire Throwing: Phoenix Immortal Fire Technique Jutsu. more than 2 hours and does not level up.

**Comment by Kiochii** [comment]
The same happens with this jutsu:

Destroyer insect neurotoxin

**Comment by IllusiveBIair** [comment]
I've renamed this issue so that we can handle all instances of this here. If any more jutsu like this are found add them here.

I know that chidori is another.

**Comment by Haikuno** [comment]
Rasenshuriken gives 0.3 XP per use.

**Comment by Tesoro2** [comment]
Chidori, is also experiencing these same issues

**Comment by IllusiveBIair** [comment]
This issue is resolved and will be coming in the next hotfix. No need to continue to report jutsu here as far as I know as I believe I found all instances of this problem.

**Comment by Haikuno** [comment]
The issue is still there for some jutsus. Rasenshuriken giving around 1 xp per use means it would take over 400 casts to max out, so I don't think that's intended. Also Chidori is giving around 0.5

**Comment by IllusiveBIair** [comment]
Solved for real this time!
